In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
data_tensor = torch.tensor(data)
print(data_tensor, type(data_tensor))

tensor([[ 1,  2],
        [ 3,  4]]) <class 'torch.Tensor'>


In [3]:
data = [[1, 2], [3, 4], [5, 6]]
np_data = np.array(data)
print(np_data, type(np_data))
np_data_tensor = torch.from_numpy(np_data)
print(np_data_tensor, type(np_data_tensor))

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6]]) <class 'torch.Tensor'>


In [4]:
torch.zeros(5)

tensor([ 0.,  0.,  0.,  0.,  0.])

In [5]:
torch.ones(2, 2)

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [6]:
torch.rand(3, 3, 3)

tensor([[[ 0.1359,  0.3735,  0.7141],
         [ 0.8875,  0.8443,  0.1779],
         [ 0.9841,  0.0849,  0.5462]],

        [[ 0.9872,  0.5453,  0.1247],
         [ 0.4945,  0.4199,  0.4176],
         [ 0.7544,  0.2381,  0.5116]],

        [[ 0.5068,  0.9172,  0.5850],
         [ 0.4682,  0.4776,  0.1193],
         [ 0.5599,  0.3770,  0.8960]]])

In [7]:
zero_tensor = torch.zeros(3, 3)
ones_like_zeros = torch.ones_like(zero_tensor)

print(zero_tensor.shape, ones_like_zeros.shape)

torch.Size([3, 3]) torch.Size([3, 3])


In [8]:
zero_tensor[0]

tensor([ 0.,  0.,  0.])

In [9]:
ones_like_zeros[:, 0]

tensor([ 1.,  1.,  1.])

In [10]:
x = ones_like_zeros.detach()
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])


In [14]:
print(ones_like_zeros)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])


In [11]:
x[:, 0] * 5

tensor([ 5.,  5.,  5.])

In [12]:
rand1 = torch.rand(5)
rand2 = torch.rand(5)
torch.matmul(rand1, rand2)

tensor(1.4071)

In [13]:
rand1 = torch.rand(5, 5)
rand2 = torch.rand(5, 5)
torch.matmul(rand1, rand2)

tensor([[ 2.5290,  2.0068,  1.4841,  0.4516,  1.5252],
        [ 2.6308,  1.5736,  1.0568,  0.2724,  1.4330],
        [ 1.9921,  1.2284,  0.7575,  0.2195,  1.0173],
        [ 1.7106,  1.3239,  0.9588,  0.5617,  0.8394],
        [ 1.5513,  1.0822,  0.8367,  0.2746,  0.7426]])